### ISSUE TITLE
TemplateDoesNotExist at /

### ISSUE THREAD

**Issue by goto1134** [lutece-awesome/lutece-backend#55]
Hi

I tried to run backend server as written in https://acm.uestc.edu.cn/develop/ and I got an error

```
Request Method: | GET
-- | --
http://127.0.0.1:8000/
2.2.2
TemplateDoesNotExist
static/index.html
/Users/User/Projects/lutece-backend/venv/lib/python3.7/site-packages/django/template/loader.py in select_template, line 47
/Users/User/Projects/lutece-backend/venv/bin/python
3.7.3
['/Users/User/Projects/lutece-backend',  '/Users/User/Projects/lutece-backend',  '/Users/User/Projects/lutece-backend',  '/Users/User/Library/Application '  'Support/IntelliJIdea2019.1/python/helpers/pycharm_display',  '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',  '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7',  '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',  '/Users/User/Projects/lutece-backend/venv/lib/python3.7/site-packages',  '/Users/User/Projects/lutece-backend/venv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg',  '/Users/User/Projects/lutece-backend/venv/lib/python3.7/site-packages/pip-19.0.3-py3.7.egg',  '/Users/User/Library/Application '  'Support/IntelliJIdea2019.1/python/helpers/pycharm_matplotlib_backend']
Tue, 2 Jul 2019 04:29:15 +0800

```

What do I need to do to fix it?

**Comment by LaPluses** [comment]
We have give up Django MVT mode, so for now the BE server is **only one API server and not provide the HTML response**. For all HTTP endpoints, you can ref to [here](https://github.com/lutece-awesome/lutece-backend/blob/master/Lutece/urls.py).
Therefore, to visit the web page, you still need to serve the [FE server](https://github.com/lutece-awesome/lutece-frontend) in your localhost.

**Comment by goto1134** [comment]
Ok, I found a way to run backend and frontend, but I can't figure out how to make them communicate

**Comment by goto1134** [comment]
and where can I get the AUTH_KEY?

**Comment by LaPluses** [comment]
Which was set within Lutece/config.py, which used to exchange data between server and judger client.

**Comment by goto1134** [comment]
Ok, I have none now.

How can I make backend and frontend communicate? Do I need to setup some configs in frontend?

**Comment by LaPluses** [comment]
By default the dev env is set up correctly, so you do not need to do anything else.
