### ISSUE TITLE
管理员权限分级

### ISSUE THREAD

**Issue by hexisyztem** [lutece-awesome/lutece-backend#60]
由于当前管理员数量过多，但是大部分管理员用户只需要查看代码功能及查看隐藏题目，并不需要过高的权限，使得安全性无法保障。考虑对管理员权限进行分级，并完善管理员操作日志，提高安全性。

**Comment by LaPluses** [comment]
Django支持权限的细分，可以考虑给定义几种不同种类的管理员，也可以给每个人单独上权限
